### ISSUE TITLE
Add a flag to exit when all connections close

### ISSUE THREAD

**Issue by imLinguin** [imLinguin/comet#25]
I believe such feature could be useful for usage as a wrapper in apps that have no direct management of comet.

I'm thinking of flag like `-q` and `--quit`.

## The flow
1. Comet started with a quit flag, waits for connection
2. Game client connects to comet
3. Game client disconnects from comet after some time
4. Comet checks if there are no other connections and exits

**Comment by kevin-wijnen** [comment]
I would like to request this to be added to the requirements:

- Set a specific amount of seconds to wait searching for new connections before quitting

The reason I ask for this, is because of the current implementation of `comet_shortcut.sh` (found in the `steamdeck` directory). Currently, after closing a game if Comet would be launched with a quit flag, it would shutdown everything a bit too quick that Heroic wouldn't be able to sync up the playtime with GOG (and possibly cloud save syncing). Hence a (configurable) waiting period is recommened.

**Comment by imLinguin** [comment]
I think it's fine for the comet to exit as soon as the last client disconnects, at the moment we don't expect the launcher to connect to comet under any circumstances

**Comment by kevin-wijnen** [comment]
> I think it's fine for the comet to exit as soon as the last client disconnects, at the moment we don't expect the launcher to connect to comet under any circumstances

After a very short "debugging session", it seems more to be a Heroic issue (only syncing up GOG playtime if the game session's at least 1 minute long, compared to any second being sent to them), than an issue with the current shortcut implementation shutting down too soon.

**Comment by imLinguin** [comment]
1 minute is the lowest value we can send GOG as far as I know

**Comment by imLinguin** [comment]
The flags were added in referenced commit. 
> After all clients disconnect comet will wait for COMET_IDLE_WAIT seconds or 15 by default

The `COMET_IDLE_WAIT` is the environment variable that can be used to control the wait duration
