### ISSUE TITLE
[Question]: What exactly does the preload command do? And how do I obtain the CLIENT_ID and CLIENT_SECRET?

### ISSUE THREAD

**Issue by mainrs** [imLinguin/comet#54]
The command requires both client id and client secret. Does preloading allow one to play games offline and sync them later up with GOG?

P.S.: Enabling the discussions page for questions like these is always nice!

**Comment by imLinguin** [comment]
Yes, the preload command essentially allows you to save necessary data to the local database allowing for use when offline. 

This utility is meant for automated use in the future. I designed it so Heroic could pre-load that data after game installation. 

In order to find them manually you should head over to gogdb and find the the entry `Game` for your title of choice. Then head over to bullds tab and pick any. If any of the online features are available the client id and secrets will be available there. E.g https://www.gogdb.org/product/1423049311#builds
